import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Theme = 'watchify' | 'catppuccin-mocha' | 'catppuccin-macchiato' | 'dracula' | 'nord' | 'tokyo-night' | 'gruvbox' | 'rose-pine' | 'one-dark';

interface ThemeStore {
  theme: Theme;
  setTheme: (theme: Theme) => void;
}

export const useThemeStore = create<ThemeStore>()(
  persist(
    (set) => ({
      theme: 'watchify',
      setTheme: (theme) => set({ theme }),
    }),
    {
      name: 'watchify-theme',
    }
  )
);

export const themes = {
  watchify: {
    name: 'Watchify (Default)',
    description: 'Original dark theme dengan hijau neon',
    colors: {
      background: '#0b0c0f',
      foreground: '#ffffff',
      card: '#14151a',
      cardForeground: '#ffffff',
      primary: '#00dc74',
      primaryForeground: '#000000',
      secondary: '#22232b',
      secondaryForeground: '#ffffff',
      muted: '#22232b',
      mutedForeground: '#a3a3a3',
      accent: '#22232b',
      accentForeground: '#ffffff',
      border: '#2a2b33',
      input: '#2a2b33',
      ring: '#00dc74',
    },
  },
  'catppuccin-mocha': {
    name: 'Catppuccin Mocha',
    description: 'Soothing pastel theme untuk mata',
    colors: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      card: '#181825',
      cardForeground: '#cdd6f4',
      primary: '#89b4fa',
      primaryForeground: '#1e1e2e',
      secondary: '#313244',
      secondaryForeground: '#cdd6f4',
      muted: '#313244',
      mutedForeground: '#a6adc8',
      accent: '#313244',
      accentForeground: '#cdd6f4',
      border: '#45475a',
      input: '#45475a',
      ring: '#89b4fa',
    },
  },
  'catppuccin-macchiato': {
    name: 'Catppuccin Macchiato',
    description: 'Variant Catppuccin yang lebih hangat',
    colors: {
      background: '#24273a',
      foreground: '#cad3f5',
      card: '#1e2030',
      cardForeground: '#cad3f5',
      primary: '#8aadf4',
      primaryForeground: '#24273a',
      secondary: '#363a4f',
      secondaryForeground: '#cad3f5',
      muted: '#363a4f',
      mutedForeground: '#a5adcb',
      accent: '#363a4f',
      accentForeground: '#cad3f5',
      border: '#494d64',
      input: '#494d64',
      ring: '#8aadf4',
    },
  },
  dracula: {
    name: 'Dracula',
    description: 'Dark theme dengan aksen purple',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#21222c',
      cardForeground: '#f8f8f2',
      primary: '#bd93f9',
      primaryForeground: '#282a36',
      secondary: '#44475a',
      secondaryForeground: '#f8f8f2',
      muted: '#44475a',
      mutedForeground: '#6272a4',
      accent: '#44475a',
      accentForeground: '#f8f8f2',
      border: '#6272a4',
      input: '#44475a',
      ring: '#bd93f9',
    },
  },
  nord: {
    name: 'Nord',
    description: 'Arctic, north-bluish color palette',
    colors: {
      background: '#2e3440',
      foreground: '#eceff4',
      card: '#3b4252',
      cardForeground: '#eceff4',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      secondary: '#434c5e',
      secondaryForeground: '#eceff4',
      muted: '#434c5e',
      mutedForeground: '#d8dee9',
      accent: '#434c5e',
      accentForeground: '#eceff4',
      border: '#4c566a',
      input: '#4c566a',
      ring: '#88c0d0',
    },
  },
  'tokyo-night': {
    name: 'Tokyo Night',
    description: 'Clean dark theme terinspirasi Tokyo malam',
    colors: {
      background: '#1a1b26',
      foreground: '#c0caf5',
      card: '#16161e',
      cardForeground: '#c0caf5',
      primary: '#7aa2f7',
      primaryForeground: '#1a1b26',
      secondary: '#24283b',
      secondaryForeground: '#c0caf5',
      muted: '#24283b',
      mutedForeground: '#565f89',
      accent: '#24283b',
      accentForeground: '#c0caf5',
      border: '#414868',
      input: '#414868',
      ring: '#7aa2f7',
    },
  },
  gruvbox: {
    name: 'Gruvbox Dark',
    description: 'Retro groove dengan warna hangat',
    colors: {
      background: '#282828',
      foreground: '#ebdbb2',
      card: '#1d2021',
      cardForeground: '#ebdbb2',
      primary: '#b8bb26',
      primaryForeground: '#282828',
      secondary: '#3c3836',
      secondaryForeground: '#ebdbb2',
      muted: '#3c3836',
      mutedForeground: '#a89984',
      accent: '#3c3836',
      accentForeground: '#ebdbb2',
      border: '#504945',
      input: '#504945',
      ring: '#b8bb26',
    },
  },
  'rose-pine': {
    name: 'Rosé Pine',
    description: 'All natural pine, faux fur and a bit of soho vibes',
    colors: {
      background: '#191724',
      foreground: '#e0def4',
      card: '#1f1d2e',
      cardForeground: '#e0def4',
      primary: '#c4a7e7',
      primaryForeground: '#191724',
      secondary: '#26233a',
      secondaryForeground: '#e0def4',
      muted: '#26233a',
      mutedForeground: '#908caa',
      accent: '#26233a',
      accentForeground: '#e0def4',
      border: '#403d52',
      input: '#403d52',
      ring: '#c4a7e7',
    },
  },
  'one-dark': {
    name: 'One Dark Pro',
    description: 'Iconic Atom theme untuk VS Code',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      card: '#21252b',
      cardForeground: '#abb2bf',
      primary: '#61afef',
      primaryForeground: '#282c34',
      secondary: '#2c313c',
      secondaryForeground: '#abb2bf',
      muted: '#2c313c',
      mutedForeground: '#5c6370',
      accent: '#2c313c',
      accentForeground: '#abb2bf',
      border: '#3e4451',
      input: '#3e4451',
      ring: '#61afef',
    },
  },
} as const;
